### ISSUE TITLE
Support X-Real-IP from nginx proxy?

### ISSUE THREAD

**Issue by dcnoren** [A21z/node-cd#16]
Basically, my NodeJS apps pulling from Github are behind an nginx proxy, and the NodeJS server has no direct internet access. Therefore, the IP the request comes from is always an internal IP. Nginx then re-writes the original IP as "X-Real-IP". Can you provide a configuration option that enables checking X-Real-IP? Wouldn't always want that as then a public-facing NodeJS server could be impacted by somebody just writing in an "X-Real-IP" header as nginx wouldn't be handling that.

**Comment by A21z** [comment]
Hi @dcnoren,

I tried an implementation in this branch: https://github.com/A21z/node-cd/tree/ip-header, could you try it and tell me if it works for you?

You basically need to add a line to config.js:
```
security: {
    useIpFromHeader: 'X-Real-IP',
    [...]
}
```

**Comment by RoosterBooster007** [comment]
Why is this issue still open? @A21z definitely fixed the problem... (I guess @dcnoren hasn’t replied though)
